language: generic
sudo: required
services: 
    - docker 
before_install: 
    - docker build -t sidradiantlogic/docker-react -f Dockerfile.dev .
script: 
    - docker run -e CI=true sidradiantlogic/docker-react npm run test