language: generic
sudo: required
services: 
    - docker 
before_install: 
    - docker build -e CI=true -t sidradiantlogic/docker-react -f Dockerfile.dev .
script: 
    - docker run sidradiantlogic/docker-react npm run test -- --coverage